

const users = [
    {
        name: "John",
        age: 30,
        city: "New York",
        country: "USA",
        photo: "https://via.placeholder.com/150",
        skills: ["HTML", "CSS", "JavaScript", "React", "Redux", "HTML5", "CSS3", "Node.js", "Express", "MongoDB", "TypeScript", "React Router", "Webpack", "Babel", "Git", "Jest", "Cypress"],
    },
    {
        name: "Jane",
        age: 25,
        city: "London",
        country: "UK",
        photo: "https://via.placeholder.com/150",
        skills: ["HTML", "CSS", "JavaScript", "React", "Redux", "HTML5", "CSS3", "Node.js", "Express", "MongoDB", "TypeScript", "React Router", "Webpack", "Babel", "Git", "Jest", "Cypress"],
    },
    {
        name: "Bob",
        age: 40,
        city: "Paris",
        country: "France",
        photo: "https://via.placeholder.com/150",
        skills: ["HTML", "CSS", "JavaScript", "React", "Redux", "HTML5", "CSS3", "Node.js", "Express", "MongoDB", "TypeScript", "React Router", "Webpack", "Babel", "Git", "Jest", "Cypress"],
    },
    {
        name: "Alice",
        age: 35,
        city: "Berlin",
        country: "Germany",
        photo: "https://via.placeholder.com/150",
        skills: ["HTML", "CSS", "JavaScript", "React", "Redux", "HTML5", "CSS3", "Node.js", "Express", "MongoDB", "TypeScript", "React Router", "Webpack", "Babel", "Git", "Jest", "Cypress"],
    },
    {
        name: "Mike",
        age: 28,
        city: "Tokyo",
        country: "Japan",
        photo: "https://via.placeholder.com/150",
        skills: ["HTML", "CSS", "JavaScript", "React", "Redux", "HTML5", "CSS3", "Node.js", "Express", "MongoDB", "TypeScript", "React Router", "Webpack", "Babel", "Git", "Jest", "Cypress"],
    },
    {
        name: "Sarah",
        age: 22,
        city: "Sydney",
        country: "Australia",
        photo: "https://via.placeholder.com/150",
        skills: ["HTML", "CSS", "JavaScript", "React", "Redux", "HTML5", "CSS3", "Node.js", "Express", "MongoDB", "TypeScript", "React Router", "Webpack", "Babel", "Git", "Jest", "Cypress"],
    },
    {    
        name: "Tom",    
        age: 27,
        city: "Moscow",
        country: "Russia",
        photo: "https://via.placeholder.com/150",
        skills: ["HTML", "CSS", "JavaScript", "React", "Redux", "HTML5", "CSS3", "Node.js", "Express", "MongoDB", "TypeScript", "React Router", "Webpack", "Babel", "Git", "Jest", "Cypress"],
    },
]
